- name: Add Prometheus Community Helm repo
  shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Add Grafana Helm repo
  shell: helm repo add grafana https://grafana.github.io/helm-charts

- name: Update Helm repos
  shell: helm repo update

- name: Install Prometheus
  shell: |
    helm install prometheus prometheus-community/prometheus \
      --namespace monitoring --create-namespace

- name: Install Grafana
  shell: |
    helm install grafana grafana/grafana \
      --namespace monitoring \
      --set adminPassword=admin \
      --set service.type=LoadBalancer \
      --set datasources."datasources\.yaml".apiVersion=1 \
      --set datasources."datasources\.yaml".datasources[0].name=Prometheus \
      --set datasources."datasources\.yaml".datasources[0].type=prometheus \
      --set datasources."datasources\.yaml".datasources[0].url=http://prometheus-server.monitoring.svc.cluster.local \
      --set datasources."datasources\.yaml".datasources[0].access=proxy \
      --set datasources."datasources\.yaml".datasources[0].isDefault=true
