---
- name: Download and install K3s master
  shell: |
    curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 644
  args:
    creates: /usr/local/bin/k3s

- name: Wait for K3s service to be active
  systemd:
    name: k3s
    state: started
    enabled: yes
  retries: 5
  delay: 5
  register: result
  until: result.status.ActiveState == "active"

- name: Ensure kubeconfig exists
  stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: kubeconfig
