---
- name: Installer Docker sur Ubuntu
  hosts: cicdhub, monitoring
  become: yes

  tasks:
    - name: Mettre à jour les paquets système
      apt:
        update_cache: yes

    - name: Installer les dépendances nécessaires
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Supprimer ancien fichier de dépôt Docker (si présent)
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Supprimer ancienne clé Docker (si présente)
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Créer le répertoire keyrings pour apt
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Télécharger la clé GPG Docker au bon format
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Ajouter le dépôt Docker avec clé GPG locale
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable\n"
        mode: '0644'

    - name: Mettre à jour le cache apt proprement
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer Docker
      apt:
        name: docker-ce
        state: present

    - name: Démarrer et activer le service Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ajouter l'utilisateur courant au groupe Docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Vérifier la version installée de Docker
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Afficher la version de Docker
      debug:
        msg: "Docker installé : {{ docker_version.stdout }}"
